kind: pipeline
type: docker
name: react-vite-build

steps:
  - name: install-and-build
    image: node:20-bullseye
    environment:
      ROLLUP_NO_NATIVE: "true"
    commands:
      - npm ci
      - npx vite build
  #      - rm -rf node_modules
  #      - npm install --ignore-optional
  #      - npx vite build
  #      - npm ci
  ##      - npm run build  # runs tsc && vite build
  #      - npx vite build

  - name: cleanup-old-image
    image: docker:cli
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - docker image rm portfoliomanager_fe:latest || true

  - name: docker-build
    image: plugins/docker
    settings:
      repo: portfoliomanager_fe
      tags: latest
      dockerfile: Dockerfile
      context: .
      push: false
      dry_run: true
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    when:
      branch:
        - master
        - main

  - name: deploy
    image: docker:cli
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - docker stop portfoliomanager_fe || true
      - docker rm portfoliomanager_fe || true
      - docker run -d --name portfoliomanager_fe --network shared-db-net -p 81:80 portfoliomanager_fe:latest

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock
